Az/pdetails
templatecookie/tc.com pull request #3
Opened 2023-07-07 11:07 UTC by pro-dev-ryan

product details page accomplished

2023-07-07 16:01 UTC, devzakir requested changes

2023-07-07 16:01 UTC, devzakir commented on components/Demo/ProductScreenshots.vue
> +import { Swiper, SwiperSlide } from "swiper/vue";
remove the import

2023-07-07 16:01 UTC, devzakir commented on components/Demo/TestimonialSection.vue
> +import { Swiper, SwiperSlide } from "swiper/vue";
remove the import

2023-07-07 16:01 UTC, devzakir commented on pages/demo/[slug].vue
>          <exclusive-feature :data="section" />
remove the imports from this file.

2023-07-07 16:02 UTC, devzakir requested changes
Please fix the conflicts. and remove yarn.lock from git history

2023-07-10 01:59 UTC, devzakir requested changes
- [ ] Design is broken, color is mismatched across the entire demo page. please check. I have added a few examples below. 

<img width="1414" alt="image" src="https://github.com/templatecookie/tc.com/assets/33604077/fe121a88-c771-4a69-ac91-be3a60cc160f">
<img width="1376" alt="image" src="https://github.com/templatecookie/tc.com/assets/33604077/ad275986-a745-4ffb-85cd-eb29f0300c4d">

<img width="1363" alt="image" src="https://github.com/templatecookie/tc.com/assets/33604077/7644ac8a-a4ef-487a-93f7-b7083fe45623">
<img width="1233" alt="image" src="https://github.com/templatecookie/tc.com/assets/33604077/58abf8a1-b22e-4e4c-bf5d-2f9c29c1cdec">

2023-07-10 10:43 UTC, closed without merging

2023-07-10 11:22 UTC, pro-dev-ryan commented on components/Demo/TestimonialSection.vue
> +import { Swiper, SwiperSlide } from "swiper/vue";
Import removed

2023-07-10 11:37 UTC, pro-dev-ryan commented on pages/demo/[slug].vue
>          <exclusive-feature :data="section" />
Done

2023-07-10 11:40 UTC, pro-dev-ryan reviewed
All redundant imports has been removed. Design fixing in progress

2023-07-11 09:05 UTC, pro-dev-ryan reviewed
All changes has been done. Please check